var tlMax = new TimelineMax();

// Type animation with GSAP
// appendBannerHTML("masthead", "./asset/banner/bupa_Bodymovin_mh/index.html");
// appendBannerHTML("halfpage", "./asset/banner/bupa_Bodymovin_hp/index.html");

 // $("#frame").attr("src", "http://ajf.resource-server.com/ajf0702_ajf_website/WP/");

// intro_Animation();
console.log('(@@) (  ) (@)  ( )  @@    ()    @     O     @'+
                     '(   )'
              );

function insert_directory(id) {
    $("<br><span class='directory shadow'>~/loft/home/</span>").insertBefore("#" + id);
}

function init_typing() {

    var easingPower4 = new gsapTypeIt({
        el: document.getElementById('block1'),
        elClass: 'intro',
        cursorSign: '_',
        word: 'Hello,welcome to <a class="homepage" href="https://www.isaacguan.com" target="_blank">[Loft]</a>',
        delay: 0,
        duration: 1,
        easing: Power1.easeIn
    });

}

function fallback_typing() {

    var easingPower4 = new gsapTypeIt({
        el: document.getElementById('block1'),
        elClass: 'intro',
        cursorSign: '_',
        word: 'Hello, welcome to Loft..<br>A place for my code<br>Please turn off the adblocker before continuing browsing this site',
        delay: 0,
        duration: 2,
        easing: Power1.easeIn
    });

}

function init_rotating() {
    var last_cursor = $(".gsapCursor");
    last_cursor.remove();

    var rotating = new gsapTypeIt({
        el: document.getElementById('block2'),
        rotateWords: true,
        cursorSign: '_',
        delay: 2,
        autoPlay: true,
        rotateWordsOptions: {
            wordsList: ['frontend tricks', 'server side configuration', 'or more...<br>'],
            cycle: false,
            clear: true

        }

    });
}

function init_showCase() {

    var last_cursor = $(".gsapCursor");
    last_cursor.remove();

    var easingPower4 = new gsapTypeIt({


        el: document.getElementById('block3'),
        charterPerSecond: 8,
        cursorSign: '_',
        word: 'I prefer color contrast and keep things simple..',
        delay: 0,

    });

}

function init_input() {
    insert_directory("block4");
    var last_cursor = $(".gsapCursor");
    last_cursor.remove();

    var easingPower4 = new gsapTypeIt({


        el: document.getElementById('block4'),
        charterPerSecond: 18,
        cursorSign: '',
        word: ' What\'s the code?',

        delay: .5,

    });

}

function close_intro() {
    var tlMax = new TimelineMax();
    tlMax
        .to(['#intro_block'], 1, { height: 0 });
}

function show_input() {
    insert_directory("question");
    $(".question").css("display", "inline-block");
    var input = document.getElementById("question_input");
    var value;

    input.addEventListener("keyup", function(event) {
        event.preventDefault();
        if (event.keyCode === 13) {
            value = input.value.toLowerCase().trim();
            if (value === "bupa") {
                // close_intro();
                appendBannerHTML("masthead", "./asset/banner/bupa_Bodymovin_mh/index.html");
                appendBannerHTML("halfpage", "./asset/banner/bupa_Bodymovin_hp/index.html");
                content_block_opening();
            }
        }
    });
}



function init_hovering() {
    $cont = $('#block1');
    parts = $.map($cont.text().split(''), function(v) {
        return $('<span />', { text: v });
    });
    $cont.empty().append(parts);
}

function fallback_Animation() {
    tlMax
        .to(['#intro_block'], 0, { opacity: 1, onComplete: fallback_typing });



    ;
}

function intro_Animation() {

    tlMax
        .to(['#intro_block'], 0, { opacity: 1, onComplete: init_typing })
        .to(['#intro_block'], 0, { opacity: 1, onComplete: init_input }, "+=2")
        .to(['#intro_block'], 0, { opacity: 1, onComplete: show_input }, "+=3")


    ;

}
// ./asset/banner/bupa_Bodymovin/index.html
function appendBannerHTML(size, path) {
    var size = size;
    var path = path;
    const Item = ({ size, path }) =>
        `<div class="${size}"><object type="text/html" class="${size}_object" data="${path}"></object></div>`;

    $(".content_block").append([{
        size: size,
        path: path
    }].map(Item));
}

function content_block_opening() {
    var tlMax = new TimelineMax();
    tlMax
        .to([".content_block"], 1, { opacity: 1, scaleY: 1, ease: Power3.easeInOut });
}



function typingAnimation_reference() {
    console.log("This typing animation is posted on this discussion forum<br>");
    console.log("https://greensock.com/forums/topic/11361-typewriter-effect/");
    console.log("Of course this is not the only way to animate things like this..");
    console.log("But it's a great extension to the official gsap packages.");
    console.beer();
    console.beer();


}


function ascii_animation(){


 $(".ascii").append(item);
}
    const item = `MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd':oxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl'coccdKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMX:.lxkxlld0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkclKMMM0;'cdk00xolo0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xol'.xWMMMO,,codOXKOkdlo0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOo:cdkl,oNMMMWx,;clokKXXOO0xlo0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOoc;;d0Od:lXMMMMNl,;::cx0XXX0O0Kxlo0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOoc:;cx0XOxlc0MMMMMO:',;;:oOXXXXKO0XKxldKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOo:;:cld0XXOkklxWMMMMXl,'',';lOXXXXXXOOXXKxlxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dc,,clldOXXXOk0doXMMMMKl,'.,,.,oOXXXXXNN0OXNX0olOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkl:,,:cllxKXXXOkKOlOMMMWOc'...'',:d0XXXXXNNN0OXNNXklxNMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdc;;,';lloOXXXXOkKKodNMMKd;'.....;clkKXXKXXXNNW0OXNNXOldNMMMMMMOo0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo:;:;'':llxKXXXX0kKNkl0WXk:'......'cox0XXK0KXKXNWN0ONNNXOlxNMMMM0:'c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx:;:;..':lokXXXXXKkKNXddKkl,'......':odkKXXOk0KO0XNWNO0NNNXOlkWMMXl,ool0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo;:;...':loOXXXXXKO0NNOcll;'........:odk0XXKxx0KkOXNWWXOKWNNXxl0MNd,cOKol0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo;;,...':loOXXXKO0OONWNd,,'.........;ldk0KXXOdx0XkkKXNWW0OXWNNKodXk:;o0XKolKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd;;'....:loOXXXXOO0OXWWKl..  .......;lox0XXXKxod0XOx0XNWMNOOWWNXOolc,;ooxXXolKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk;;'....;llkXXXX0k0O0WWN0;.   ......,lodOXNXXOdox0XOdOXXNWWKkKWNXXx,'';c.'kNKolKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMM0:,'....,cldKXXXKdx0OXWWNk' .'......,codkKXXXKxoox0X0oxKXNWWWOONX0XKl..;;''c0W0coXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxKMMMMMMMMMMMMMMKl;,.....:lo0XXXXxlkO0WWWXd''lc.....'cooxKXXXXkccld0XKdo0XXNWWXk0XOKNk'.,,;c;cKKxcdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'cXMMMMMMMMMMMMNd;,.....,llkXXXXOloOOXMWXd;;lkl....'coox0XXXX0o;:ld0XKdlOXXNWWW0kX0OXKc..';dl'dXOdldNMMMMMMMNXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd..oNMMMMMMMMMMWk;,......:ld0XXX0ocxO0NMXo;:cdKo...':oodOXXXXKkc,;ld0XXxlxKXNNWWNkOXOOXk,.';xO:,kKOxlkWMMMMMNolXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.',xWMMMMMMMMMKc,'.....,lokXXXKxclkO0WXo;cloOXo...:oodkKXXX0ko:,,cd0XXxld0XXNWMW0kKKkKO:'';xKd,c0OOdlKMMMMXo';0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:,:,;kWMMMMMMMNd;'......:okKXXXOo:oOKXKl;colxXXd..;lookKXXXKxlc;',cd0XXklokXXNWWWNkONOko,'.;xK0l,dOOOoxWMMKl;ccOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;;::::kWMMMMMWk:,......'cd0XXX0xc:d0X0c;lollONNx..;lookKXXX0o::,.,ld0XXkllxKXXNWMW0xKXo,'..:xKXx::xkkxoKWKc,okcxMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk,,::lc:kWMMMMKl,.......;oxKXXKkl;cxKO:,:loldKNNk'..:ood0XNKxc:;'.;ld0XXOlldOXXNWMWNkOKl'..'cx0X0d:lxodoxOc,cO0cdWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd'';:cdo:kWMMNd;'......'coOXXX0o;,ckx:',;lolxXWWO,..'cookKX0o::,..;ld0XXOllokKXNWWWW0xl,...;od0XXkl:looo:,';dKKloNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo'''::lxdckWMO:,.......;ld0XXKx:',ll;''':ollONWWK:...,lodO0xc;;'..;ld0XXOllox0XNNWMWXd'...'codOXN0xl:lc:,',lOXXolXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc''.;c:okdcxKo,'.......:okKXXOl;';;''..,lolo0NWWXl....;oodxl:,...';lx0XN0olodOXXNWMW0c....:ccdOXNKkdc;;,'':xKXXdlKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:''.,cccdOxc;;,.......,ldOXXKx:,.......:ooldKNWWNd.....:oolc;'...';lx0XX0olookKXNWW0c....;:;cdOXXKkOd'''.;oOXXNxc0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:''..:l:cx0k;.........;ld0XX0o;'......'coolxXNWWWO,....,coc:,....':lxKXX0oloox0XNXk:'...,:',ldOXXKkKO;..,lxK00Nx:OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;,'..,ll:lx0k:........:ox0KXkc,.......;ooolxXNWMWKc....;cc:;'....,:oxKXX0oloodOXOl,'...,:,.;ldOXX0OXKc..:dOXOONx,kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;,'...coccokKOc......'coxk0Kd:..'.....:xxolxX0XWWNd...,:::;'....',cokKXXKoloooxd:,'...,:,.':ox0XXOONXo',lxKKO0Nd'dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;,'...;loccokK0l.....,ldxkKOo,.''.....:kOdlxKO0WMW0:.':;,;,.....',cokKXXKocooc;,,....,:,..,ldOXXKOKWKl,:dOX0x0Nx,dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;,'...'cooccox00d,...;lddkKkc',,......:k0klxX00NMWNd',;.',......';loxO0XKocc;,,'....,c;...:dOKXX0ONWOc,cxKXkdKXk:oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'''....,lolcclok0x;..:lolx0x:';,......:kKOodK0ONMMWKl,........'',;looodxxc,,,,.....,c;...,lkKXXXO0WNk;;o0XXxdKXOloXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,.......:oolcclox0kc',cl:ldo;':,......;kKKxoOKOKWMWNk,........'',:looooo:'','.....;c;...'cxKXXX0OXWKo,:kKX0oxXKOooXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0NMMMMMMMMMMMO;.......'coolclold00o;',;lol,':,......,dKXOxOXO0WMWWXd.......',,,;loooc,,,'.....';c;....:xKXXXXO0WWO:;o0XXklxXK0xoKMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,,d0WMMMMMMMM0;........,looocclloO0xc'.;ll,':,......'oKXKOOX0OXMMWNKc......',,,,;::;,,'......':c;....:x0XXXXKOXWXd,cOXXKdlkX00koKMMMMMMMMMXkoOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc .'cxKWMMMMMK:,'.......;ooooccolox0kl,',;'':,.......l0XXKOKKO0WMMWNO;.....',,,,'..,,......',cl;....;d0XXXXX00WNO:;dKXXOllkK0KkdXMMMMMMW0d;.;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO' .'',cxKWMMXl,,........:oool::llldOOdc,'..;;.......:OXXXKKXOONMMWNXk,.....'''..','.....'';ll;....;d0XXXXXKOXWKo,lOXXXx:lO00KdxWMMMMXkl:;;,dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl...;:;',cd0Xo,;.........:oool;;lolok0xl:'.,;.......,x0KXXXXKkOXWMNKKd'.......','......',:ll,....;d0XXXK0KXXWNk::kXXX0l:o00K0dOMMN0dc::cdlc0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0, ..;c:'..,:,';'........'coooc;;lollxOOdc',;.......'o0xkKXXXOxkXMWKO0o......,'.......',coc,....:d0XXXKOOXWWW0l;oKXNXx::d00XkxXXxl::lllkOcdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo....':c,.....,,.........':oooc;:looloO0x:,;'.......cOxcxXXXKkxONMNOkOc..,,'.......',:loc'....:d0XXXKkkKNWWXd;cOXXN0l;cxKNXococ:cooldOKd:0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;.....;c:'...';.......'..':oolc;;coollx0x;;,.......;xOc;kXXX0xx0WMXkxxc'.........',:lo:'...'cx0XXX0xdOXWMNOc;xXXNXk::lkKOo;;clodddkKXk:oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd......,cl;'..,,......';'.':ool:,;:looldkl;,.......'o0d,;kXXXOxkKWWXkdd;.......',;col:'...'cx0XXX0xdxOKWWKo;oKXXN0o;:ccc;;coodxxk0XXOc;OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;......':lc,..,'......,:,..:ool:,,;cooll:;,........:Ok:.;kXXKkxOXMWKxdo;.....',:lol;....,lkKXXX0xodkOXWXx:c0XXXXx;',,,;clodkkkOKXXOl,lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.......';llc'.,'......,c;..;lol;,',:coo:,,'.......,dOo'.;kXX0xxONMWKxolc;'',,clol,....,lkKXXXOdooxk0WNOc:kXXXKx:,',;:cldk0OOKXXX0d;;OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc......'',col;,;'......;c:..;lol;,'',:ll;,'........ckx:..;kXXkxk0WMWKxoolc;:cooc,....;okKXXKOdccdxONWKo:dKKkdc;,,,;:coOK0O0XXXXKxc,lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'......'',:lo:,;'......;lc'.,loc;,'',;:;,,........,dxo,..;xXKkxxkKK0koooolloo:'....:okKXXKko:;cdkXWXx::ddc;,''';:ldOXKOOK0kOXXkl:;OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.......',,;ll:,;,......:lc'.,clc;'''','','........cddc'..,dK0docclloooooool;....':odxkOOxl,.:dx0WNOc,;:,,..',:lxKXX0OK0kdd0Xkoc,lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0, ......',,;cl:,;,......:lc,.';;,,,'.''.,'........,loo;...,lxddddxdoc:cool,....,loooooooc'.,odONWKd,','...,:okKNXOO0KOdlxKXOoc;;OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd........'',,:c:,;;......:ll;..'..'''...',.........;::;:ldO0KXXKXXXKOkoc:'....;looccll:;..'ldkXWXx;....';cx0NWXOxO0OdllxKXkl:;,lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK: ........',,;::,;;......;oo:'.....''...''.........cx0KKKKKKXXXK0Okkxxc'...':llccokKKkc..:dxKWWOc...,:okKNWXkdxOOxlclxKKkl:;,;OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk..........'',,;:,;;'.....;oxl,......,clollldxd:.,d0K0KKXXNXK0OkkkkOOOOOd:,:lccdOXXXXXOo:,lOWWKd;,:lxOXWWKkooxdolccokK0xl:,;,oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl...........',,,;,,:,.....,oxd:...'lO0OO0KXX0d:ck000XNXK0000KKK0Okxddddxxl;cdOKXXXXKK0kxocdOkdoodk0NWNKkdloolccccdO0Ool:',;:0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;...........'',,,'':;.....,lkx;.:k0O0KNXK0d:;oO0OKX0kxk0XXKOxdooocc;,,;:ccdxdx0XXKO00kkkc;odoodx0KKOxdoolccc:cox0Odl:,.':;dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'............',,'''::'.....:::dOO0XNX0ko:,;dOOOK0xddOKKOkxxdllc:,''....,clc:lkKXOdkOkkOl:dkOkdoodoooolccc::cdk0ko:,..':;lXMMMMMMMMMMWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxOKNWMMMMMMMMXl.............'''''';:'.....:k0OKNX0xo;..:dOOOOxddx0K0kxdoc;'''........,;'..'l0Xklx0kO0ll0OOOOkdllolccc:;;cdOOdc;...,:;lKMMMMWNX0OkdccOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:..;codk0XNWMM0:..............'','',:;...ck00XX0kl;'..,o00OkdodkKKOoc;,''''''.........',;;,:OKxcxX00O::kKK0O0KOo:;c:,',cxkdl;'..';::o0K0Okkxxxxd:':OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd'....'',:ldxkl'...............',''';''ck00XKko:'...,:xK0xoodO0kl;''................,,'.';ckOocxK0Kx',coOKX0OXNd,''.,oxdl;'...,:;;lxxdoodkKX0x:,oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c.....'''..''..................',..':oOXKOdc,'...,;:xOxoodkkl,'........................;cxxcckKXKc..:clx0X00WO,..:odl:'...';;;coddxkOOK0Odc,cOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx'....''''''.....................';;lO0ko:''....,';oooodkd:,.........'',;;;;::'.......,coo:ckXNk'...;ccoOKNW0;,cooc,....,;,;ldxk0XNXOxlc;;dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl......'',''..................',',lxdl;'......,.,lccdxo:'.. ....',;;cloxkO00xc,... .,:l;,lkX0c''..'cccd0NW0:coc;....';:ldOKNNNNKxollc;c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;.......',,,'...............,..'coc,'.......,..,;ldo:'. ....,;::cxOKXNNNNNNKd:'. .,:,';oO0l..;,..;::oOXWO:;;....',:oOXNNNNKkdlcll:;xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo'........'','........... .,...;c;'...... .'...;ol:'.  ..';:::ckXNNNNNNNNNN0l;. .'..'cxOl.. .;,.'';oONWk'.....,:oONWWNKkolclooc;l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c..........'','''........''...,,......   ....:cc,. ..';::::ckXNNNNNNNNNNNKo:,.....:xxc,,'. .,...:x0XNd;cc'':o0NWNKOdlcllool::xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;...........'''''''................ ......':c;. .';::::::dKKKNNNNNNNNNNXx:,....;olcdkl;...'..,oxO0d,cOKol0NNXOxlcllooooc;oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd'..............'','.'.........'.  .,....';:' .,;:;,,;;:oxdONNNNNWNNNNNkc'...'::oOXXx:'..'.'coxd:,,;o0ddK0xoclloooool:cOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo'.................'. ......... .co;....;;..';;;;,'...',:kNWWWWWWNNNNO:..'''ckXNK0d;...'':llc:;;:oK0lldoooollllll::xXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo'...............'.  ....... .oXX0l...,' .,:lo:;;,.. .,kWMWWNNNNKkdc..'';xXX0OkOkc..',;;'..lkdxKNx:loolccc:::::o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKx:'............'. ........ 'ldOKO;..'. ..;cxOd:;;,..'xWWNNXX0xc;,...'cOKOkO0KKOo..,,''. .'dKNN0c:lcc:;,',;:lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdc,.........''.... ....  ..'dk:........;ckK0dcc:,:ONNNKxoc:;,...,:dkOO0OOOo'...,:oc,'..;kNXo,::,,'.',:oONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXko:'.....';,..   ...  . .cKk'..cd:...;ckXXKOkxkKNXOl:::;,.',;cdkOOO0KXKl...;dKx;'..';kXx,','.',cdkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXKOdc'.. .,'.      .  ....xXo.,xkxdc,,;ckXWWNNNNN0l,;;;;,;:ldkxxkKNMMNd;',oKNO;... .c0k,.'',cdOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0o:'...........'..         ...'k0cdNKoldolc;lONWNNXKX0:...';:ldxxdoxXMMMNkooxKNWKc..,,;l0k:;;;,,:clooodx0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xl;'.............       ....,ddx00Odoodxoco0NOk0O0k;..';ldOkdddxOKKK00OKNNNNNo.,oxx0Kd,.,,;;;;;;::cokKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdl;'........'..    ..........'',;cllc:cdloOkOx;;cccloddlccllooddxk0XNWNx;,;coxd:'.',;:lodk0XNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOdl;'....''........ .....''''........';;::;;,''........'';coxO0XWWO::llldolodkO0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxl:'.............',;:lxO0Oko;'.. .,oOko:;'....';cok0XNNNNWWKc:lcd0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0;... ..........',;cdOK0d:'.. .;kNNXX0kdlldk0KXNNNNNNWWXl,dOlxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,................',;:l:'. ....,kNWNNNNXXXNNNNNNNNNNWWNd,;o0xoXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.....  .............''.. ..,..,kWWNNNNNNNNNNNNNNNNWWNx,;okXOo0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl... .. ............... . ..;..,xKKNNNNNNNNNNNNNNNWWNx;cOXNWKokMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;....... .......................;lOXXXNNNNNNNNNNNWN0c':ONNNNNxxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXd'.......   .............. .     .o00000KKKNNNNNNXOc..;kXNNNNNklONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0dl;............  .............   ...,dO0KXXNNNNNNNKx:...'dKNNNNNNOclxxOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOo:'........'........   ...... ......  .'lk0KXNNNNNKkl,....'l0NNNNNNN0d0N0kxxkKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOd:'...... ...''''........   ........... ..cKNNNNNNKko,.....,;cOXNNNNNNN0odKNWNX0kxk0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkdxOXKxc'....      ...'''''':c. ... ..  ...........;kKKK0xl,.. ...:c;;dXNNXO0NNNK:.:lx0XNWN0kkk0NMMWNKKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xoldOkc.   .,,....         .'''''',,cxc.    .....  .........,;;,'.   ...;odc,c0NNXklxXNNKc...';cd0XNWNKOkkxl:,;lx0X0dodkKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0d:.....      ........     .....'''''.';ckO;.   .......  .................;oOOl,;kXNN0l:oKNNXd;'..',;:oOXNWWN0o;. .;::;.....';lx0NWMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxlokKNKx:..   ..      .........   ..''..''''''..,:xXx.   .................',;,..';lkK0o;,oKNNOc::l0NN0o::;,',;:::ok0XNNWXx;.,cc:,. ......';lxKNN0xl:l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXKx,....';'.      ..       ...........,;;;,'''''''...;oKXl.  ........   ..';lxxl::;;:dKNKx:,c0NNO:,;;cONXxc:::::;;:::::cdOKNNWKc;ccc;. .:olc;,...';;.   .,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXK0Oxdolc:;;,''.........        ..       .........';;:::;,''''''....:kNK:...........  .'o0NXx:;;::l0NXkc,;xXWKl';::ckXkc;;:::::::::::::cokKNk::cc:'  .lOOOOkdlc;'.    ..'cdxO0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOxol:,'..               ...           .        ........';::::::;''''''.. .,dXWO,.......'''.. 'xXXkc;;;::dKXOl,'oKNNx'.;:::dxc'..',;:::::::::::::lo:,ccc;. .'oO000000Okxl.   .......',;clodkOKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKOdl;'..                       ..            .        .......'',;;;;,,,''''''... .c0NWk' ......',;,.'dKkc:::::ckXOl;':ONW0:..,::::;.......',;:::::::::::,';clc.  .;x0000000000x'   ...  ..........'',;cloxkOKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkl,.                             ...            .        ........'''''''........... .,xXWNd........',;;;ldc::::::o00o;';dXNWx. ..;:;'.. ........',;:::::::;''ccc,. ..ckO000000O0Oo.    ..    ...'cdddooooooooodddxxkkO0XNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;                  ......         ...            ..       .......................... ..cONWNd. ......',;;:::::::::oxl,',l0NWNo.....'.. .............';:::::,';cl:.  .,oO000000000k;    ...    ..'lk000000000000O00OOkxddddd0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.           ............          ...            ..        ...........   ..   ....   .';oKNWNo..........',;;::::::c:,.':xXNWNo......   ...............',;:,.,clc,   .:k0O000OO00Oo.   .l:.    .,oO000000O000000OOOO00000OOloNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.         .............           ...            ..        .     ...',;:cllooodddddooooddxOOOx:.  ..........',,'''....,cx000Ol''',,,;;;;;;,,''....    ...'.,cll:.  .'oO0000000O0k,   .ckl.. ..,oO0000000O000000000O000000klxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:         .............             ..            ..        .';cldxO0KXNNNWWNNNNWWWWWWWWWWWNNXK0xo:,..    ...... . ...,cdkOO000KXXXNNNNNNNNNXXXK0Okdol:,...':clc'   .:k000000000Ol.   ;kOo'...;dO0O0000000000000000O000OO0x:oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXx;.         .............              ..            ..       .lO000OOkkkkkkkxxxxxxkkOO00KXNNNNNWWWWWNX0xoc;,'....'',:lxOKNNWWWNNNNNNNNNNNNNNXXKKKKKKKXXXXXk;':ccc;.  .'oO00000000Od'   ,xOOo'..:xO0000000000000000000000O000o,,cd0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo'            ............                .            ..        .',,,'.....',;:coddxxkkOO0KXXNNNNNNNNNNNWWWWWNKK0OO00KXNNNNNNNNNNNNNNNNNNNNXK0kdllcc:::cclll:;:llc:'   .:k000000000x,   .dOOOd,'ck0000000000000000000O0000000Oc,::;;lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl.              ............                .            ...             ....';codxkO000KKKKXXXNNNNNNNNNNNNNNWWMMXkdoooooooodddxxkkO00KXXNNNNNNXXXXKKKK00OOOkc',c::cc,.   'oO00000000Ol.  .lOOOOd:lk00000000000000000000OO000000x;,cccc:;l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMXo.                ............                             ...             ..',,;;;;;;::::cccllooddxkO0XNNNNNNNNNWWO:',::::::::::::::::cloddxO0KXNNNNNNNNNWWN0d::;'.;c:.   .:x0OO000000k:  .lOOOOOkxO00000000000000000000000000O00o,;cccccc:;oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWO;                  ............                             ....               ............'',,,,;;;;::cokKXNNNNNNWWk'..,;;;;;;;;;;::::::::::::cldkOKXNNNX0xo:,;,.. 'cc'    .lO0OO00000Oo. .cO000O00O00000000000000000000000000000Oc,clccccccc:cOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMNd.        .          ............                              ....                  ...............'',,;;::lx0XNNNNNNd. .........'',,;;;:::::::::::::coddol:::;,..  .:c,.   .;x0O0OO0000k; .:k00000OO00000000000OOO0000000000000000x;;cclccccccc:;dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMXl.       .';.         ............                              ..'.                  ..  ......   ......',,;;:lxKXNNNNo. ..............'',;;:::::;,,,,,;;::ccc;..   .,c;.    .lO000OO000Ol..:k000000OOO0000000000kdxO000000000000OOOl':llllcllllll:;oXMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMXc        .,c:.         ............                              ..';.                 ........      .......'',;::lkXNNXl. ..................'',,,,,;;;;;;::cc;..     .::.    .,x000000000x'.;k000000Odok0000000000k::xO0000000000O00k;.':cclcllclllcc;dNMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNo.       .,cc;.         ............                              ..'c,                   ..,;;;,''..............,,;;lOKKc.         .........',,;;;;,,,,,;:cc;..      .;:.     .cO00000000O:.;x0000O0Oo,ck0000000000x;.;xO000000OO0000d.  .:clcllllllclc;xNMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWk.       .,ccc;.          ...........                              ...cl.                     ..,;:ccccc::;;,,,,,',,,,,;cc;'..''''''',,;;;::::;,'....',;cccc;..       .;:.      ,d00000000Oo';x00000Okl''cO0000000000x;..:xOO000O00OO0Oc.   .:cllllllclll::OWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMX:        ,cccc,.            .........                              ...cd,                         .....'''',,,,,;;;;;;;;;;;;;;;;;;;;;,,,''........,;:ccccc;..      ..'::.      .ck0000OOO0k:;x00000Ox:..'oO0000000000d,...:xO00O00O000x'     .:cllcccllclc:lXMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMk.       .:cccc,               .......                              ...;xl.                                                                  ..,;cccccccc;..    ..';:cc;.      .'dO000OxxOOocxO00O0Od;...,dO000000000Oo,....:x00000000Ol.      'cccccccccccc:kWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWK:       .;ccccc,                ......                               ..'dk;                                                             ..',;cccccccccc;.. ..',;ccccc:,.       .ck00Okl:x0xoxO000Oko,....;x0000000000Oo'.....:k0000000k;       .,ccccccccccc;;dKWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMKl.        'cccccc,                  ....               .               ..'lOo.                                                        ..',:ccccccclccc:;,'',;:ccc::;,...   ..  ..:xO0Oo;,lOOkkO0000kc......:k0000000000Ol'......ck000000o.        .:ccccccccccc::cxNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWo.         .',;:cc'                    ..               ..              ...:kOc.                                                ...',,;ccccccccc::;;;;:;::cc::,,'..      ....  ..cx0Oxc'.ckOOO00000x:.......lO0000000000Oc.......'ck00O0k;         .;ccccccccccccc;lXMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMKl.       .'.......                                      .              ...'oOk:                         ............''''',,,,;::cccccccc:::;;;;;;::cc:;,'...         .';;'.  .'lkOko,..;xO0OO0000x;.......'oO0000000000k:........'oO0OOo.         .,c::ccccccc::cxXMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWKl.      ..,;;'...                                     ..              ...,oOk:.                       .',:ccccccccccccccc::;;,,''',,;;;;;::c::;,'...            .';::,.  ..;dOOx:...,dO000000Od,........;d00000000000x;.........;x00k:           ...,ccccc:,;dXWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMM0:'.       ..,::;.                                    ..               ...'lkkl.                         ..,;:::;;,''.......'',,;::ccc:;,'....              ..,:cc:,.   .'cxOko,...,oO000000Oo'.........:k00000000000o'.........,d00d.            .;ccc:;cddlOMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMXl'...         .'.                                     .                ....;dkd;.                           ...  ....'',;:ccc:;,,,'...                  ..,:ccc:,.   ..,oOOx:'...'oO000000Ol. .........cO0000000000O:..... ....ck0k:           .,:c:;,:xKWKoOMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWx,...... ..                                           ..                ....'cxkl'                   ........'',;::ccc:;,,'...                      ..';cclccc,.    .'cxOkl,....'oO000000kc. .........'oO0O00000000d,....  ...,d0Oo.         .'::,''';xXNW0o0MMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMKc'........ .'''..                                    ..                 .....,okxc.                  ...',,;:::;,,'...                          ..,:cclllc:,.    ..,oOOd:.....'oOOOO000k:.  .........,x0O00000000Oc....   ..'lO0k;        .';;;' .;:ckNNNkdNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWk;..... ....ck0kl,..                                 ..                   ....':dkx:.                       ...                             ..,;ccccccc:,'.    ..'cxOkl,.....'oOOOOOOOx;.   .........:k0000000000x;....   ..:kOOl.       .':oxOc..;:l0NWKdOMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMNx,.... ....cONX0l;..                               ....                   .....'cxkd:.                                                 ..';:ccccc:,'..      ...;dOOd;......,oO0OOO0Ox,.    ........'lO00000O0O00l....    .;dOOd.      ..;xKNNXl.,:cxXWXxxNMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMK:.... ....;xXNXkc,.                               ....                     .....,lkOx:.                                           ..';:cc:;,'...         ...,lkOkl'......,oO0000OOd'      ........,dO000000O00k;       .'oOOx,   ..',;:xXNNNKl';:dKNXdlKMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWk;..... ...'o0NNXxc,.                              .. .                      ......;okOxc'                                     ..';;:;,'...             ...'cxOOd;.......,dO00000Oo.       ........:k00000000OOo.      ..lOOx,.  .';::::dXNNNO:,:o0NKxddOWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMXl'.........,:xKNNXkl;'.                            ..  .                       ......;dkOko,.                               ....'....                  ..':dOOkl,.......;dO00000Ol.        .......'lO000000000k:      ..:kOd,. ...,:::::xXNNXd,:xKXOdON0xXMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWO;'..  .....,;cxXNNX0o:,.                           ... .                         .....':dO0Od;.                                                      ...;ok0Od;........:xO00000k:.        ........;x0000000000d.    ...;xkl.......;::::lONNNOcoOKOoxKNWXxOWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNo'... .......';cxKNNXOl;'.                          ...  .                         ......':dO0Oxc.                                                  ...;ok0Okl,........:k000000x;.         ........ck000000000O:    ...,dx:.......,::::cxXNNOdk0xl;:kNNNWkdXMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMO;'. ...,;;;,,'',:dOKkc'....''.                      ...  .                           ......':dO0Okl'.                                             ...,lkO0Od;........'ck00000Od,           .......'oO000000000d'  ....,ll'.    .';::::cxKNXkllc;;;::dKNNWKd0MMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWd,'. ...;::::::;;;:c:'...';:::;.                     .... ..                            ......'cdO00Oo;.                                         ...,lxO0Oxc'........,lk00000Ol.            .......;x000000000Oc......'::,'''',:lc:;,;lOXXk:.....;:::oKNNWNdkWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNo''.....;::::::::::'. .';:ldoc:;..                   ....  .                             .......':dO00Od:.                                     ...'cxOO0ko;.........,dO00000kc.              ....':dO000000000x,..  ..,,,;:::oOXNXKOxddxo;..  ..';:;:dKNNWWxdNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWx,'.....,::::::::;'...,:lxKXKd::;..                  ..... ..                              .......':dO00Oxl'.                                ...':dOOOOx:'.........:xO0000Ox;.               ..;lxOOOO0000000Ol.   ...';::::dKNNNNNNNNX0d:......,:::cONNNWWxoNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMXl''.....,::::::;'..';:o0XNNNKo::;...                ..... ..                                .......':okO00ko;.                            ...':dOOOOkl,.........'ckOO000Oo'              .':oxOOOOOOOO000000x,   .....',;;:dOXNNNNNNNNNNXO:...,:::cxXNNNWWxdNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMK:'.....';::::;....;:oKNNNNNN0l::,....              ...... .                                  ........,lxOO0Od:.                       ....';okOO0Od;..........,oO00000Oo.           ..;cdk0000OOOOO0000000Ol.  .  ..  ...,;cokKXNNNNNNNNNO;..;:::dKNNNNWXoxWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMW0;.'.....;:::,....;:lONNNNNNNXOl::'.... .;.         .........                                  .........':dkOOOxl'.                  .....;ok000Oxc'.........':xO000000x,         .':okO000OkdooxkO00000000k;...........  ..;::lkKNNNNNNNNNx..;:::xXNNNNWOcoXMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWO;.......';::,....,;:xXNNNNNNNNXkc:;.....'xc          ........                                    .........';lxO00ko;.              .....;ok0000ko,..........,okO00OkkO0d'     .';lxOO0OOxol:,...';lxOO0000Oo,;:,......... ...,::cd0XNNNNNNNXl.,:::oKNNNWXodOxXMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWk;..  ....;::;....';:lONNNNNNNNNNXxc:,....;ko          .........                                     ..........,cdk00Ox:.           ....,lk0000Od:'.... ....':xO00Okl:d00k;...;cdkO0Okxoc;'..........,cdO000kcoXx,......... . ..,:::lOXNNNNNWMKc,;::ckXNNNko0NOxXMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWO;..   ...,;:;.. ..;::xXNNNNNNNNNNNKxc;....:0d.         ..........                                      ..........';lxOOOxl,.         .,lxO0000kc'....  ....;oO000ko;':x00OkddkOOOkdlc;'..'',;;:cclooddxkO000dl0Mk;..   ...  .....;:::ckXNNNWMMWO;,:::dKNNNxoKWNkxNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMM0:..   ...';::'. ..'::l0NNNNNNNNNNNNNKd:,..'lXO'         ..........                                        ...........':oxO0Ol.       .;dO0000ko;....  ....'ckO00Od:'.'lO00000OkxdolcccloodxxkkOOOOO000000000OldNMKc..   .        ..;:::ckXNNWMMMWd,;::lONNNOlxNWXxkWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMXl..    ...;::;.  ..;::xXNNNNNNWWWWWNNNKd;..,xWNc            .........                                        ............,:lc,.      .'oOOO0Od:'...   ...':dO00Oxc'..,cx000000OkkkkOOO0000000O000000000O00000dl0MMNd'.... ....... ..';:::lOXNWMMMMXl,;::xXNNXlcKWWKdOMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWd'.    ...,:::'.  .'::lONNNNNNNWMMMMWNNNk:'':0MMKc.             .........                                       ..............        .ck0OOxc,...    ...;ok00Okl,',:oxOO000000000000000000000000000000000000OldNMMMO;.. . ...........,::::l0NWWMMMMO;,::oKNNNx:kNWWkdXMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMM0;..   ...';::;.  ..;::xXNNNNNNWMMMMMWNNXx:;'oNMMMWOl'.             ........                                        ........          .,d00ko;...    ...'lkOO0koc:ldkO000OO0000000000OOOOOOkkkkkxxxxdddddkO000xl0MMMMNo'.... .... ......;::::oKNWMMMMNd,;:cONNNO:dNNWXdkWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMNo'..  ....;:::,. ..';:lONNNNNNNWMMMMMWNN0l:,;OMMMMMMWXOl,.              .......                                       ....           ..lOOd:...    ...':dOOOOOxxxOO000OOOkkxxdooollcc:::;;;,,,,''''...',lxO00OldNMMMMMO;.... ...........';:::cxXWWMMMMK:,::dXNNKllKNWWOoKMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMO;.. .....,:::;. ...,;:dKNNNNNNWMMMMMMWNXx:;,oNMMMMMMMMMMNOo,                ....                                                    ..;dxc'..    ....;okOO000O00OOkdocc:;,,''........................;lxO0000dl0MMMMMMNl'................,::::lONWWMMMNd,,:l0NNNOkXNNWXdxWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWd'.. ....';:::;. ..';:ckNNNNNNNWMMMMMWNNOl:,;OMMMMMMMMMMMMMM0'                                                                      ..';c,..     ...,cxO00O00Okxoc;,...............          ......':okO0000OxlxNMMMMMMMO;................';::::oKNWWWWW0:,:ckXNNNNNNNWWkoXMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMXc........,::::,. ..'::l0NNNNNNNWMMMMWWNKd:;,dNMMMMMMMMMMMMMMNc                                                                      ......     ...':dOOOOOkxl:,'..........               ........,cdOO00OOxddxONMMMMMMMMNl'................,::::ckXNNNNNXd,;:o0NNNNNNNNW0oOMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMO;.......';::::,. ..;::dKNNNNNNNNWWWWNNNOc;,cKMMMMMMMMMMMMMMMWx.                                                                    .....     ....,okOOOxoc;'.......                   ........':okO00Okddxk0NWMMMMMMMMMMMO;.............. .';::::o0NNNNNNO:,::lOXNNNNNNWNdxWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWx,.......,:::::;....;:ckXNNNNNNNNNNNNNNKo:,,kWMMMMMMMMMMMMMMMMK;                                                                             ...':xOkdl:,......                    .........';lxO00Oxl;.,OWMMMMMMMMMMMMMMMNo'................,::::ckXNNNNNXl';;;lOXNNNNNWWxdNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWd'.......;:::::;...';:cONNNNNNNNNNNNNNXkc;,oNMMMMMMMMMMMMMMMMMWd.                                                                          ....,oxdc;'.....                     ..........,cdkOOkdc,.  .lNMMMMMMMMMMMMMMMMMK:'...............';::::oKNNNNNNd,:dl;l0NNNNNWWkdXMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWo.......';:::::;...';:l0NNNNNNNNNNNNNN0l;,cKMMMMMMMMMMMMMMMMMMMK;                                                                         ....,cc;'....                      ..........,cokOOko:'.     'OMMMMMMMMMMMMMMMMMMWx,................;::::ckNNNNNNd':O0l:kXNNNNNW0dKMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMNo.......'::::::;'..'::l0NNNNNNNNNNNNNXx:,:OMMMMMMMMMMMMMMMMMMMMWx.                                                                     .......'.....                      ..........':okOOko:..       .lNMMMMMMMMMMMMMMMMMMMNl'...............,:::::dXNNNNXo'ckXOcdXNNN00WKd0MMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWo.......,:::::::'...;:l0NNNNNNNNNNNNXOc,;kWMMMMMMMMMMMMMMMMMMMMMNo.                                                                  ............                       ..........'cdOOOd:.           'OMMMMMMMMMMMMMMMMMMMMMK:'..............':::::oKNNNN0:,ckNXdl0NNN0xKKd0MMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWd.. ....;:::::::;...';cxXNNNNNNNNNNXOl,;kWMMMMMMMMMMMMMMMMMMMMMMMXl.                                                               ..........                         ...........,colc;'.            .dWMMMMMMMMMMMMMMMMMMMMMWO;'.............';::::o0NNNXo,;lONNk;dNNNXxOKx0MMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWx.  ...'::;;::::cl' .';ckXNNNNNNNNKkc,c0WMMMMMMMMMMMMMMMMMMMMMMMMMNk:'..                                                          ........                            ...............               .lXMMMMMMMMMMMMMMMMMMMMMMMWk;'.............;::::dKNNXx,,:oKNN0coXNNNOxxxKMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMO'.. .';:;,,:::::dx,...;cd0XNNNX0xl;;dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKOkxo:.                                                   ......                                                           .'ckNMMMMMMMMMMMMMMMMMMMMMMMMMWk;,'..........';::::xXNXx;,:cxXNNXkxXNNNNkcdXMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMO,...';:;',;:::::o0k,...';cdkOxoc;:o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:                                                  .....                                                       ...,:lx0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c,''........,::::cONKo;;::o0NNNNXXNNNNNNxoKMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMW0c...';:,.';::::::ckXO;. ..,;:;;;cxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.                                                ...                                                        ...:kKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOo:,,,'''',;::::lkd;';::cxXNNNNNNNNNNNWNOd0WMMMMMMMMMMMMMM
MMMMMMMMMMMMWO:...,:;'..;::::::::dXN0c...''''c0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk;.                                                                                                     ...';c,cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkoc:;;;:::::;;'..,:::lONNNNNNNNNNNNNWWKdOWMMMMMMMMMMMMM
MMMMMMMMMMMNx,...';;'. .;::::::::oKNNK:..':ll0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.                                                                                               ..',;::cc::;lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOl,''',;;'. .;:::lONNNNNNNNNNNNNNWWXxkNMMMMMMMMMMMM
MMMMMMMMMMXo'....':;....,::::::::oKNWWk,':xOdKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.                                                                                            ....''''',,,,oONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc,'...'. .';::::oKNNNNNNNNNNNNNNWWXdxNMMMMMMMMMMM
MMMMMMMMMNo'.....,:,....';:::::::o0NWWK:,:xOd0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk'                                                                                                 ..',;:c:;kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl,,...  ...;:::::dKNNNNNNNNNNNNNNWWXdxNMMMMMMMMMM
MMMMMMMMWd,.... .,;......;:::::::oKNNWK:':o0xxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.                                                                                            ..',;:ccccc;,lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc,...   ...';::::ckXNNNNNNNNNNNNNNWWKokWMMMMMMMMM
MMMMMMMMO;..... .,,......;:::::::dKNNWO,':lOOo0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.                                                                                    ....',;:::::;;,'',';OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd,'..   .....,:::::o0NNNNNNNNNNNNNNWWWOo0MMMMMMMMM
MMMMMMMNo........''......;:::::::xXNNWd.';ckXkdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.                                                                                    ................,:;:0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;'...   ......;:::::xXNNNNNNNNNXNNNNWMNdxNMMMMMMMM
MMMMMMM0;...............';::::::cONNWXl.,:l0NKdOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.                                                                                           ..',;;:cc:;''dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl''...   ......':::::l0NNNNNNNNNKKNNNNWMOo0MMMMMMMM
MMMMMMWd'...............,:::::::l0NNWXc';ckXWXdkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc                                                                                      ...',;:::;;,',,,',;dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;,....   ......';::::ckXNNNNNNNN0OXNNNWMXokWMMMMMMM
MMMMMMXl................;:::::::dKNNWKc':xXNWXdkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;                                                                                 .....''''..........,,':0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd,,....   .......;:::::dKNNNNNNNN0dONNNWMNdxWMMMMMMM
MMMMMMK:...............':::::::ckXNNNOc:xKNNW0o0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;                                                                                      .....'''.... .;c;cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl,;....   .......;:::::o0NNNNNNNNOcdXNNWMWxdWMMMMMMM
MMMMMMO;.......  ......;:::::::oKNNNNklxKNNWNxdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc                                                                             .....'',,,,,'...    ..;c:;dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl,;....   .......;::::;lONNNNNNNNk:l0NNWMWxxWMMMMMMM
MMMMMMk,.......  .....';::::::ckXNNNXkxKNNNW0o0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkc.                                                             .........'',,;;;,,'...........'',,;;;lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl,;'....   ......;:::::lONNNNNNNNd;ckNNWMNdxWMMMMMMM
MMMMMMk,.......  .....,:::::::o0NNNNNXXNNNWXdxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.                                            ..                  .  .....  ............';;:::cclolcoXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd,;,. ..  .......;:::::lONNNNNNNXo,:xXNWWXdkWMMMMMMM
MMMMMWx,.......    ..';::::::cxXNNNNNNNNNWNxdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:.                    ............. ...';:clloddddool' ....,;;:::::::::;.'::cccclloooodo;:dxkkOO000Oo';OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk,;;...... .... .,:::::l0NNNNNNN0:':dKNWWKoOMMMMMMMM
MMMMMMk,......   .  .,:::::::o0NNNNNNNNNNWOo0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd.                      ..............;oxkOO0000000000O:..;ldOOO000000000Ol;dO00000000000Ol:x000000000k:.'oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:,;,............,:::::o0NNNNNNNk'':dKNWWOdKMMMMMMMM
MMMMMMO;......   ....;::::::ckXNNNNNNNNNWKokWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:                       ..............:kO00OO0000000000k;.,dOOOOOO000000OOOk:;x000000000000o;oO00000000Oo'..;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd,;;............,:::::dKNNNNNNXo',:oKNWWxdNMMMMMMMM
MMMMMM0:......    ..,:::::::o0NNNNNNNNNWXxxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.                        ...........;;.cO000OOO000000000x,.:k00O0O0000000000Oo,ck00000000000x,:k000000000k:...:xXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:,:,...........,:::::xXNNNNNNO:';:dKNWXdkWMMMMMMMM
MMMMMMKc......    ..;::::::ckXNNNNNNNNWNkxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl.                 ..     ...........;l,.cOO00OO0000000000d..cO0000000000000000k;'lO0000000000k:'oO00000000Ol..'cooKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk;;;.. ........,::::ckNNNNNNXk;,::dXNW0dKMMMMMMMMM
MMMMMMNo'.....    .';::::::oKNNNNNNNNWWOdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:..                ..      ..........;do..cO0000O000000000Ol..cO0000000000000000Oo',dO000000000Oc.;x000000000x,..ckdlOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd,;,.  .......,::::l0NNNNNNNk;;::kXNNkxNMMMMMMMMM
MMMMMMWk,.....    .,::::::cONNNNNNNNWW0dKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,..               ....      .........,dk:..lO00000000000000O:..cO00000000000000000x;.:x000000000Ol.'o000000000O:..:kOdlkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo,;'.........,::::oKNNNNNNKl,::lONWKx0MMMMMMMMMM
MMMMMMM0:.....    .,;;;;,,ckKKXNNNNWWKx0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'..               ....      .........'oOd'..lO00000000000000k, .:k00000000000000000Ol..ck0000000Okl'.cO00000000Ol..;x0OxldNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl,,.........,::::xXNNNNNNk;;::dKNNOxNMMMMMMMMMM
MMMMMMMNo..        ....  .':cclodk0NXk0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd..                ....       .........:kOl..'lO00000000000000d. .:k0000000000000O0000d,.'oO000000Ool;.:k000000000x,.,d00OkldXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc,,.       ....,lkkO0KK0c,;:ckXNKx0MMMMMMMMMMM
MMMMMWXk:.               .,cccc::;:ccdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd..                ....        .........ckO:  'd0OO00000000000Ol.  ;k000000000000000000k:..;xO00000x:c:.cO000000000k;.'oO000kloXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:'.          .';;::::c:,',,:x0XOkNMMMMMMMMMMM
MMMMWk'                  .,;::cccccc:;dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.                ....         .........:kk;  ,xOxk00000000000k;   ,x000000000000000000Ol...ck0000Oo':c,lO000000000O:.'oO0000kloXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0;            .,:ccccccccc::;::coKMMMMMMMMMMMM
MMMMNl                 .';;;;;:ccccc::xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,..                ....        ..........;xk: .ckocx00000000000d'   ,x0000000000000000000d'..,d0000Ol''cokO000000000Ol.'o000000kcoXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:               .,ccccccccccccc;lKMMMMMMMMMMMM
MMMMMk.                .:cccccccccc::xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc..                .....        ..........,dOc..ok::x0000000000Ol.   'd0000000000000000000d,..,dO000Oo'.,oO0000000000Ol.'oO000000d:xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;             .':ccccc:;;:cccccc:OMMMMMMMMMMMM
`;
// ascii_animation();